# Generated by Django 4.1.3 on 2022-11-17 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('trash', models.ImageField(null=True, upload_to='trashes/')),
                ('latitude', models.FloatField(default=0.0)),
                ('longtitude', models.FloatField(default=0.0)),
                ('owners', models.ManyToManyField(related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
