# Generated by Django 4.1.3 on 2022-11-22 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('trash', models.ImageField(blank=True, null=True, upload_to='trashes/')),
                ('target', models.ImageField(blank=True, null=True, upload_to='target/')),
                ('sick', models.ImageField(blank=True, null=True, upload_to='sick/')),
                ('sil', models.ImageField(blank=True, null=True, upload_to='sil/')),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longtitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('owners', models.ManyToManyField(blank=True, null=True, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
