# Generated by Django 4.1.3 on 2022-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_name',
            field=models.ImageField(blank=True, null=True, upload_to='name/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_name_color',
            field=models.ImageField(blank=True, null=True, upload_to='name_color/'),
        ),
    ]
