# Generated by Django 4.1.3 on 2022-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='trash_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
