# Generated by Django 4.1.3 on 2022-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_dictionary', '0003_alter_animal_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='trash_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
